// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "تیم توسعه اپلیکیشن",
            "url": "https://github.com/Offline-Devs",
            "email": "support@noshirvaniacademy.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh": {
            "post": {
                "description": "با استفاده از توکن تازه‌سازی، توکن دسترسی جدید ایجاد می‌کند",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "احراز هویت"
                ],
                "summary": "تازه‌سازی توکن دسترسی",
                "parameters": [
                    {
                        "description": "توکن تازه‌سازی",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "توکن جدید با موفقیت ایجاد شد",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "درخواست نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "توکن تازه‌سازی نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/request-otp": {
            "post": {
                "description": "کد OTP را برای شماره تلفن کاربر ارسال می‌کند",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "احراز هویت"
                ],
                "summary": "درخواست کد OTP",
                "parameters": [
                    {
                        "description": "شماره تلفن",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.RequestOTPInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "کد OTP با موفقیت ارسال شد",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.OTPResponse"
                        }
                    },
                    "400": {
                        "description": "درخواست نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-otp": {
            "post": {
                "description": "کد OTP را تأیید می‌کند و توکن‌های JWT برای کاربر ایجاد می‌کند",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "احراز هویت"
                ],
                "summary": "تأیید کد OTP و ورود کاربر",
                "parameters": [
                    {
                        "description": "شماره تلفن و کد OTP",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.VerifyOTPInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "احراز هویت موفق",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "درخواست نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "کد OTP نامعتبر یا منقضی",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "کاربر غیرفعال است",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blog": {
            "get": {
                "description": "تمام نوشته‌های منتشر‌شده را دریافت می‌کند (بدون نیاز به احراز هویت)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "بلاگ"
                ],
                "summary": "دریافت لیست نوشته‌های منتشر شده",
                "responses": {
                    "200": {
                        "description": "لیست نوشته‌های منتشر‌شده",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.BlogPost"
                            }
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "یک نوشته بلاگ جدید را ایجاد می‌کند (فقط برای مدیران)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "بلاگ"
                ],
                "summary": "ایجاد نوشته بلاگ جدید",
                "parameters": [
                    {
                        "description": "اطلاعات نوشته",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.BlogInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "نوشته با موفقیت ایجاد شد",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.BlogPost"
                        }
                    },
                    "400": {
                        "description": "درخواست نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "عدم اجازه دسترسی",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blog/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "اطلاعات یک نوشته بلاگ را بروزرسانی می‌کند (فقط برای مدیران)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "بلاگ"
                ],
                "summary": "بروزرسانی نوشته بلاگ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "شناسه نوشته",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "اطلاعات جدید نوشته",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.BlogInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "نوشته با موفقیت بروزرسانی شد",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "درخواست نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "عدم اجازه دسترسی",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "یک نوشته بلاگ را حذف می‌کند (فقط برای مدیران)",
                "tags": [
                    "بلاگ"
                ],
                "summary": "حذف نوشته بلاگ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "شناسه نوشته",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "نوشته با موفقیت حذف شد",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "عدم اجازه دسترسی",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blog/{id}/publish": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "یک نوشته بلاگ را برای عموم قابل دسترس می‌کند (فقط برای مدیران)",
                "tags": [
                    "بلاگ"
                ],
                "summary": "انتشار نوشته بلاگ",
                "parameters": [
                    {
                        "type": "string",
                        "description": "شناسه نوشته",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "نوشته با موفقیت منتشر شد",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "عدم اجازه دسترسی",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/blog/{slug}": {
            "get": {
                "description": "یک نوشته منتشر شده را با استفاده از slug آن دریافت می‌کند (بدون نیاز به احراز هویت)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "بلاگ"
                ],
                "summary": "دریافت نوشته بلاگ با slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "نشانی URL نوشته",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "نوشته بلاگ",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.BlogPost"
                        }
                    },
                    "404": {
                        "description": "نوشته یافت نشد",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "خطای سرور",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "بررسی می‌کند که آیا سرور در حال اجرا است",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "عمومی"
                ],
                "summary": "بررسی وضعیت سرور",
                "responses": {
                    "200": {
                        "description": "سرور فعال است",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/majors": {
            "get": {
                "description": "لیست تمام رشته‌های موجود را دریافت می‌کند",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "دروس"
                ],
                "summary": "دریافت تمام رشته‌ها",
                "responses": {
                    "200": {
                        "description": "لیست رشته‌ها و دروس",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handler.SubjectConfig"
                            }
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "description": "لیست دروس مرتبط با یک رشته تحصیلی را دریافت می‌کند",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "دروس"
                ],
                "summary": "دریافت دروس بر اساس رشته",
                "parameters": [
                    {
                        "type": "string",
                        "description": "نام رشته (ریاضی، تجربی، انسانی)",
                        "name": "major",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "لیست دروس",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.SubjectConfig"
                        }
                    },
                    "400": {
                        "description": "رشته نامعتبر",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.AdminNote": {
            "type": "object",
            "properties": {
                "admin_id": {
                    "type": "string"
                },
                "attachment_url": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "string"
                },
                "jalali_date": {
                    "type": "string"
                },
                "student_profile": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile"
                },
                "student_profile_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.BlogPost": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.Exam": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "dynamic_fields": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "jalali_date": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "student_profile": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile"
                },
                "student_profile_id": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.ExamSubject"
                    }
                },
                "title": {
                    "type": "string"
                },
                "total_subjects": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.ExamSubject": {
            "type": "object",
            "properties": {
                "answered": {
                    "type": "integer"
                },
                "blank": {
                    "type": "integer"
                },
                "correct": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "exam_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "subject_name": {
                    "type": "string"
                },
                "total_questions": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "wrong": {
                    "type": "integer"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.MistakeAnalysis": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "dynamic_fields": {
                    "type": "object",
                    "additionalProperties": true
                },
                "exam": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.Exam"
                },
                "exam_id": {
                    "type": "string"
                },
                "exam_subject": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.ExamSubject"
                },
                "exam_subject_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "question_number": {
                    "type": "integer"
                },
                "student_profile": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile"
                },
                "student_profile_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile": {
            "type": "object",
            "properties": {
                "admin_notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.AdminNote"
                    }
                },
                "approval_date": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "dynamic_fields": {
                    "type": "object",
                    "additionalProperties": true
                },
                "exams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.Exam"
                    }
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "jalali_birth_date": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "last_submitted_at": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "mistake_analyses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.MistakeAnalysis"
                    }
                },
                "profile_photo": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "school": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "study_plans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudyPlan"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.User"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.StudyPlan": {
            "type": "object",
            "properties": {
                "assigned_by": {
                    "type": "string"
                },
                "attachments": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jalali_end_date": {
                    "type": "string"
                },
                "jalali_start_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "student_profile": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile"
                },
                "student_profile_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_yourusername_noshirvani-academy_backend_internal_domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "student_profile": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.StudentProfile"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_handler.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_yourusername_noshirvani-academy_backend_internal_domain.User"
                }
            }
        },
        "internal_handler.BlogInput": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean",
                    "example": false
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handler.OTPResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "otp sent"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "internal_handler.RefreshTokenInput": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_handler.RequestOTPInput": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+989123456789"
                }
            }
        },
        "internal_handler.SubjectConfig": {
            "type": "object",
            "properties": {
                "major": {
                    "type": "string"
                },
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "internal_handler.VerifyOTPInput": {
            "type": "object",
            "required": [
                "code",
                "phone"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "+989123456789"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"توکن JWT - فرمت: Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "توضیحات API",
        "url": "https://github.com/Offline-Devs/noshirvani-academy"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "نوشیروانی آکادمی API",
	Description:      "API برای سیستم مدیریت آکادمی نوشیروانی\nشامل خدماتی برای احراز هویت، مدیریت دانشجویان، آزمون\u200cها، اشتباهات و مقالات بلاگ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
